import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';

const PETALS=[[3,-3,13],[9,-9,17],[15,-1,15],[21,-12,19],[28,-6,14],[34,-16,21],[41,-4,16],[47,-11,18],[53,-2,13],[59,-14,20],[65,-7,15],[71,-18,22],[77,-5,17],[82,-13,19],[87,-1,14],[91,-10,21],[95,-6,16],[98,-15,18]];
const routeKey=pathname=>pathname.replace(/\/+$/,'')||'/';
const getAudioSrc=theme=>theme?.audioSrc||theme?.audioUrl||theme?.musicSrc||theme?.src||'';
const getAudioTitle=theme=>{if(theme?.title)return theme.title;const src=getAudioSrc(theme);if(!src)return'';try{return decodeURIComponent(new URL(src,location.origin).pathname.split('/').pop()||'')}catch{return src.split('/').pop()||''}};
const findPageMusic=(music,pathname)=>{const key=routeKey(pathname),theme=music?.[key]??music?.[pathname]??music?.[`${key}/`];if(theme)return theme;return Object.entries(music||{}).find(([route])=>routeKey(route)===key)?.[1]??music?.['/']};

export function SakuraPetals({settings}){const amount=Math.max(0,Math.min(PETALS.length,Number(settings?.effects?.petalAmount??PETALS.length)));if(settings?.effects?.showPetalsOnInteriorPages===false||amount===0)return null;return <div className="sakura-layer" aria-hidden="true">{PETALS.slice(0,amount).map(([left,delay,duration],index)=><i key={`${left}-${delay}`} className={`sakura-petal sakura-petal--${(index%5)+1}`} style={{left:`${left}%`,animationDelay:`${delay}s`,animationDuration:`${duration}s`}}/>)}</div>}

export function SiteExperience({content,settings}){const location=useLocation();const[introVisible,setIntroVisible]=useState(false),[playing,setPlaying]=useState(false),[musicError,setMusicError]=useState('');const audioRef=useRef(null);const theme=findPageMusic(content.music,location.pathname);const audioSrc=getAudioSrc(theme);const audioTitle=getAudioTitle(theme);const controlText=content.shared?.musicControl||{};
useEffect(()=>{if(settings?.effects?.showOpeningAnimation===false)return;try{if(sessionStorage.getItem('ss-opening-seen'))return;sessionStorage.setItem('ss-opening-seen','true');setIntroVisible(true);const t=setTimeout(()=>setIntroVisible(false),content.opening?.durationMs||2350);return()=>clearTimeout(t)}catch{}},[content.opening?.durationMs,settings?.effects?.showOpeningAnimation]);
useEffect(()=>{setPlaying(false);setMusicError('');if(audioRef.current){audioRef.current.pause();audioRef.current.currentTime=0}},[audioSrc,location.pathname]);
useEffect(()=>()=>audioRef.current?.pause(),[]);
const stopMusic=()=>{if(audioRef.current){audioRef.current.pause();audioRef.current.currentTime=0}setPlaying(false)};
const startMusic=async()=>{if(!audioSrc){setMusicError('No MP3 saved');return}const audio=audioRef.current;if(!audio)return;setMusicError('');try{if(audio.getAttribute('src')!==audioSrc){audio.src=audioSrc;audio.load()}audio.volume=.28;await audio.play()}catch{setPlaying(false);setMusicError('Tap again to play')}};
return <>{introVisible&&<div className="site-opening" style={{background:content.opening?.background||'#8d1820'}} aria-hidden="true"><span>{content.opening?.mark||'S/S'}</span></div>}<audio ref={audioRef} src={audioSrc||undefined} loop preload="none" playsInline onEnded={()=>setPlaying(false)} onPause={()=>setPlaying(false)} onPlay={()=>{setMusicError('');setPlaying(true)}} onError={()=>{setPlaying(false);setMusicError('MP3 unavailable')}}/><button className={`music-control ${playing?'is-playing':''}`} type="button" onClick={()=>playing?stopMusic():void startMusic()} aria-label={`${playing?controlText.pauseAria||'Pause':controlText.playAria||'Play'} ${audioTitle} page music`} aria-pressed={playing}><i aria-hidden="true"><b/><b/><b/></i><span title={audioTitle}>{musicError||playing&&audioTitle||controlText.idleLabel||'Play music'}</span></button></>}

export function SiteHeader({content,active,tone='light'}){const[open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);const links=content.shared.navigation;useEffect(()=>{const onScroll=()=>setScrolled(scrollY>24);addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>removeEventListener('scroll',onScroll)},[]);useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);return <><header className={`sub-header sub-header--${tone} ${scrolled?'sub-header--scrolled':''}`}><Link className="sub-brand" to="/" aria-label="Saffron and Silk home"><span>{content.shared.monogram}</span><b>{content.shared.brandName}</b></Link><nav className="sub-nav" aria-label="Primary navigation">{links.map(link=><Link key={link.href} to={link.href} aria-current={active===link.href?'page':undefined}>{link.label}</Link>)}</nav><Link className="admin-portal-link" to="/admin">Admin</Link><button className={`sub-menu-toggle ${open?'is-open':''}`} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Close menu':'Open menu'}><i/><i/></button></header><div className={`sub-mobile-menu ${open?'is-open':''}`} aria-hidden={!open}>{links.map((link,index)=><Link key={link.href} to={link.href} onClick={()=>setOpen(false)} style={{transitionDelay:`${90+index*50}ms`}}><small>0{index+1}</small>{link.label}</Link>)}</div></>}

export function SiteFooter({content}){const shared=content.shared;return <footer className="site-footer"><div className="footer-brand"><div className="footer-mark">{shared.monogram}</div><h2>{shared.brandName}</h2><p>{shared.footer.description}</p></div><div><h3>{shared.footer.findUsTitle}</h3><p>{shared.footer.address.map((line,index)=><span key={`${line}-${index}`}>{index>0&&<br/>}{line}</span>)}</p><a href={`mailto:${shared.email}`}>{shared.email}</a></div><div><h3>{shared.footer.hoursTitle}</h3><p>{shared.footer.hours.map((line,index)=><span key={`${line}-${index}`}>{index>0&&<br/>}{line}</span>)}</p><Link to="/contact">{shared.footer.contactLink}</Link></div><div className="footer-bottom"><span>{shared.footer.copyright}</span><span>{shared.footer.credit}</span></div></footer>}
