import { useEffect, useRef, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';

const PETALS=[[3,-3,13],[9,-9,17],[15,-1,15],[21,-12,19],[28,-6,14],[34,-16,21],[41,-4,16],[47,-11,18],[53,-2,13],[59,-14,20],[65,-7,15],[71,-18,22],[77,-5,17],[82,-13,19],[87,-1,14],[91,-10,21],[95,-6,16],[98,-15,18]];
const midiToHz=note=>440*Math.pow(2,(note-69)/12);

export function SakuraPetals({settings}){const amount=Math.max(0,Math.min(PETALS.length,Number(settings?.effects?.petalAmount??PETALS.length)));if(settings?.effects?.showPetalsOnInteriorPages===false||amount===0)return null;return <div className="sakura-layer" aria-hidden="true">{PETALS.slice(0,amount).map(([left,delay,duration],index)=><i key={`${left}-${delay}`} className={`sakura-petal sakura-petal--${(index%5)+1}`} style={{left:`${left}%`,animationDelay:`${delay}s`,animationDuration:`${duration}s`}}/>)}</div>}

export function SiteExperience({content,settings}){const location=useLocation();const[introVisible,setIntroVisible]=useState(false),[playing,setPlaying]=useState(false);const audioRef=useRef(null),fileAudioRef=useRef(null),intervalRef=useRef(null),masterRef=useRef(null),nextNoteRef=useRef(0),stepRef=useRef(0);const theme=content.music?.[location.pathname]??content.music?.['/'];const controlText=content.shared?.musicControl||{};
useEffect(()=>{if(settings?.effects?.showOpeningAnimation===false)return;try{if(sessionStorage.getItem('ss-opening-seen'))return;sessionStorage.setItem('ss-opening-seen','true');setIntroVisible(true);const t=setTimeout(()=>setIntroVisible(false),content.opening?.durationMs||2350);return()=>clearTimeout(t)}catch{}},[content.opening?.durationMs,settings?.effects?.showOpeningAnimation]);
useEffect(()=>{setPlaying(false);if(intervalRef.current)clearInterval(intervalRef.current);intervalRef.current=null;if(fileAudioRef.current){fileAudioRef.current.pause();fileAudioRef.current=null}if(audioRef.current){void audioRef.current.close();audioRef.current=null}},[location.pathname]);
useEffect(()=>()=>{if(intervalRef.current)clearInterval(intervalRef.current);fileAudioRef.current?.pause();if(audioRef.current)void audioRef.current.close()},[]);
const stopMusic=()=>{if(intervalRef.current)clearInterval(intervalRef.current);intervalRef.current=null;if(fileAudioRef.current){fileAudioRef.current.pause();fileAudioRef.current.currentTime=0;fileAudioRef.current=null}if(masterRef.current&&audioRef.current){masterRef.current.gain.cancelScheduledValues(audioRef.current.currentTime);masterRef.current.gain.setTargetAtTime(0,audioRef.current.currentTime,.08)}setTimeout(()=>{if(audioRef.current)void audioRef.current.close();audioRef.current=null},300);setPlaying(false)};
const startMusic=async()=>{if(!theme)return;if(theme.audioSrc){const audio=new Audio(theme.audioSrc);audio.loop=true;audio.volume=.28;fileAudioRef.current=audio;await audio.play();setPlaying(true);return}const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const context=new AC();await context.resume();const master=context.createGain(),filter=context.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1150;filter.Q.value=.7;master.gain.value=.055;filter.connect(master);master.connect(context.destination);audioRef.current=context;masterRef.current=master;nextNoteRef.current=context.currentTime+.06;stepRef.current=0;const stepLength=60/(theme.tempo||70)/2,notes=theme.notes?.length?theme.notes:[50,57,60,64];const schedule=()=>{while(nextNoteRef.current<context.currentTime+1.4){const step=stepRef.current,osc=context.createOscillator(),gain=context.createGain();osc.type=theme.wave||'triangle';osc.frequency.value=midiToHz(notes[step%notes.length]);osc.detune.value=step%4===0?-4:3;gain.gain.setValueAtTime(.0001,nextNoteRef.current);gain.gain.exponentialRampToValueAtTime(step%4===0?.30:.18,nextNoteRef.current+.04);gain.gain.exponentialRampToValueAtTime(.0001,nextNoteRef.current+stepLength*1.8);osc.connect(gain);gain.connect(filter);osc.start(nextNoteRef.current);osc.stop(nextNoteRef.current+stepLength*1.9);nextNoteRef.current+=stepLength;stepRef.current+=1}};schedule();intervalRef.current=setInterval(schedule,500);setPlaying(true)};
return <>{introVisible&&<div className="site-opening" style={{background:content.opening?.background||'#8d1820'}} aria-hidden="true"><span>{content.opening?.mark||'S/S'}</span></div>}<button className={`music-control ${playing?'is-playing':''}`} type="button" onClick={()=>playing?stopMusic():void startMusic()} aria-label={`${playing?controlText.pauseAria||'Pause':controlText.playAria||'Play'} ${theme?.title||''} page music`} aria-pressed={playing}><i aria-hidden="true"><b/><b/><b/></i><span>{playing?theme?.title:controlText.idleLabel||'Play music'}</span></button></>}

export function SiteHeader({content,active,tone='light'}){const[open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);const links=content.shared.navigation;useEffect(()=>{const onScroll=()=>setScrolled(scrollY>24);addEventListener('scroll',onScroll,{passive:true});onScroll();return()=>removeEventListener('scroll',onScroll)},[]);useEffect(()=>{document.body.style.overflow=open?'hidden':'';return()=>{document.body.style.overflow=''}},[open]);return <><header className={`sub-header sub-header--${tone} ${scrolled?'sub-header--scrolled':''}`}><Link className="sub-brand" to="/" aria-label="Saffron and Silk home"><span>{content.shared.monogram}</span><b>{content.shared.brandName}</b></Link><nav className="sub-nav" aria-label="Primary navigation">{links.map(link=><Link key={link.href} to={link.href} aria-current={active===link.href?'page':undefined}>{link.label}</Link>)}</nav><Link className="admin-portal-link" to="/admin">Admin</Link><button className={`sub-menu-toggle ${open?'is-open':''}`} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?'Close menu':'Open menu'}><i/><i/></button></header><div className={`sub-mobile-menu ${open?'is-open':''}`} aria-hidden={!open}>{links.map((link,index)=><Link key={link.href} to={link.href} onClick={()=>setOpen(false)} style={{transitionDelay:`${90+index*50}ms`}}><small>0{index+1}</small>{link.label}</Link>)}</div></>}

export function SiteFooter({content}){const shared=content.shared;return <footer className="site-footer"><div className="footer-brand"><div className="footer-mark">{shared.monogram}</div><h2>{shared.brandName}</h2><p>{shared.footer.description}</p></div><div><h3>{shared.footer.findUsTitle}</h3><p>{shared.footer.address.map((line,index)=><span key={`${line}-${index}`}>{index>0&&<br/>}{line}</span>)}</p><a href={`mailto:${shared.email}`}>{shared.email}</a></div><div><h3>{shared.footer.hoursTitle}</h3><p>{shared.footer.hours.map((line,index)=><span key={`${line}-${index}`}>{index>0&&<br/>}{line}</span>)}</p><Link to="/contact">{shared.footer.contactLink}</Link></div><div className="footer-bottom"><span>{shared.footer.copyright}</span><span>{shared.footer.credit}</span></div></footer>}
